Repository efficience-it/efficience-it.github.io, pull requests merged in 2025-03, with the labels that each got.

#2 Astid fontaine patch 1
  README.md
Labels: documentation, good first issue

#3 Create htmlint.yml
  .github/workflows/htmlint.yml
  index.html
  quizz_symfony.html
Labels: enhancement

#6 fix/check-answers-and-css
  index.html
  quizz_symfony.html
Labels: bug, enhancement, question

#7 fix/ add category path
  quizz_symfony.html
Labels: documentation, question

#8 GA integration
  index.html
  quizz_symfony.html
Labels: bug

#9 add .ico
  favicon.ico
Labels: documentation

#11 Show uuid, & set help on one line
  quizz_symfony.html
Labels: enhancement

#14 Update README.md
  README.md
Labels: documentation

#13 Feat/ add twig quiz access and translations
  index.html
  js/quiz-twig.js
  js/twig-quiz-topics.js
  quiz-twig.html
Labels: good first issue, question

#15 Separate in folder assets
  .gitignore
  assets/js/common.js
  assets/js/gtag.js
  assets/js/quiz-twig.js
  assets/js/quiz_symfony.js
  assets/js/twig-quiz-topics.js
  index.html
  quiz-twig.html
  quizz_symfony.html
Labels: enhancement

#16 add contribution link & ico as svg
  .github/workflows/htmlint.yml
  assets/img/favicon.svg
  favicon.ico
  index.html
  quiz-twig.html
  quizz_symfony.html
Labels: bug, documentation, help wanted

#19 Fix: backtick code display
  assets/js/quiz-twig.js
  assets/js/quiz_symfony.js
  index.html
Labels: enhancement
